"""Report generator for enriched SOLACE items."""

from __future__ import annotations

from typing import Any

from reports.schema import ReportData, generate_report_id


def generate_report(target: str, target_type: str, enriched_items: list[dict[str, Any]], entity_map: dict[str, Any] | None = None) -> ReportData:
    source_count = len(enriched_items)
    findings = [f"Collected and enriched {source_count} seed-backed intelligence item(s) for {target}."]
    if entity_map:
        findings.append(f"Resolved {sum(len(v) if isinstance(v, list) else 1 for v in entity_map.values())} candidate entity reference(s).")
    report = ReportData(
        report_id=generate_report_id(target),
        subject=target,
        subject_type=target_type,
        classification="TLP:WHITE",
        confidence="MEDIUM",
        confidence_score=0.65 if source_count else 0.25,
        executive_summary=f"SOLACE completed a local seed collection and enrichment cycle for {target}. The report is generated without external API dependencies and is suitable for analyst review and follow-on collection planning.",
        key_findings=findings,
        entity_map=entity_map or {},
        timeline=[{"date": "collection", "event": f"Seed collection completed for {target}"}],
        behavioral_indicators=["No behavioral anomalies assessed from seed-only collection."],
        threat_assessment={"level": "LOW", "rationale": "Seed-only local collection does not establish elevated threat."},
        source_log=[{"collector": item.get("collector_id", "SEED"), "url": item.get("source_url", "seed://local"), "hash": item.get("content_hash", "")} for item in enriched_items],
        gaps=["Configure external collectors for broader source coverage.", "Run analyst validation before operational use."],
        analyst_notes=["Generated by deterministic v1 pipeline."],
    )
    report.to_markdown()
    return report
